### PR TITLE
add mod setting and flag protections

### PR DESCRIPTION
**Pull request by Ramiels**
still needs to be tested and QA'd but this looks right to me, can't be bothered to do it right now

### CODE REVIEW

**Comment by Ramiels** [comment]
my bad, had all the checks flipped. could have been catastrophic

**Comment by Ramiels** [comment]
seems more clever to automatically block these functions from a table of function names and generate a warning print to log instead of hardcoding it, that's beyond me/the scope of this for now though

**Comment by dextercd** [comment]
Looks good to me :-)

One improvement is that you can prevent someone from overwriting `ModSettingGet` and circumventing these checks by adding this line near the top:

```lua
local ModSettingGet = ModSettingGet
```

(You may want to do this for all global functions used by the script: `print`, `GamePrintImportant`, `tonumber`, etc)

<hr>
This following part is just my idea of one of the components at making this more automated. Makes sense if you consider this out of scope.

Unlike the `EntityKill`, these guards are very similar, they either allow you to use the function or not. You can automate the creation of these guard functions like this:

```lua
local function MakeAllOrNothingGuard(func_name)
    local original = _G[func_name]
    local function guarded(...)
        if ModSettingGet("Copis_Twitchy_Lua.chaos") then
            return original(...)
        else
            print("[CopiTLua]: Prevented " .. func_name .. " from being called")
        end
    end

    return guarded
end
```

Instead of writing a guard version of each function, you can now do this:

```lua
local guarded_ModSettingSet          = MakeAllOrNothingGuard("ModSettingSet")
local guarded_ModSettingSetNextValue = MakeAllOrNothingGuard("ModSettingSetNextValue")
local guarded_AddFlagPersistent      = MakeAllOrNothingGuard("AddFlagPersistent")
local guarded_RemoveFlagPersistent   = MakeAllOrNothingGuard("RemoveFlagPersistent")
```

**Comment by Ramiels** [comment]
@dextercd I've finally remembered to merge this PR, if you want to move your code to a new PR to add the `MakeAllOrNothingGuard` functionality I think the mod would be in a good place to be uploaded?

**Pull request merged**
